Repository vormkracht10/laravel-seo-scanner, pull requests merged in 2024-01, with the labels that each got.

#53 [Fix] Decode gzip content to prevent uncheckable page content
  src/Checks/Meta/DescriptionCheck.php
  src/Seo.php
  tests/Checks/Meta/DescriptionCheckTest.php
Labels: bug

#54 [Feature] Add translated descriptions to checks
  resources/lang/en.json
  resources/lang/nl.json
  src/Checks/Configuration/NoFollowCheck.php
  src/Checks/Configuration/NoIndexCheck.php
  src/Checks/Configuration/RobotsCheck.php
  src/Checks/Content/AltTagCheck.php
  src/Checks/Content/BrokenImageCheck.php
  src/Checks/Content/BrokenLinkCheck.php
  src/Checks/Content/ContentLengthCheck.php
  src/Checks/Content/KeywordInFirstParagraphCheck.php
  src/Checks/Content/KeywordInTitleCheck.php
  src/Checks/Content/MixedContentCheck.php
  src/Checks/Content/MultipleHeadingCheck.php
  src/Checks/Content/TooLongSentenceCheck.php
  src/Checks/Content/TransitionWordRatioCheck.php
  src/Checks/Meta/DescriptionCheck.php
  src/Checks/Meta/LangCheck.php
  src/Checks/Meta/OpenGraphImageCheck.php
  src/Checks/Meta/TitleLengthCheck.php
  src/Checks/Performance/CompressionCheck.php
  src/Checks/Performance/CssSizeCheck.php
  src/Checks/Performance/HtmlSizeCheck.php
  src/Checks/Performance/ImageSizeCheck.php
  src/Checks/Performance/JavascriptSizeCheck.php
  src/Checks/Performance/ResponseCheck.php
  src/Checks/Performance/TtfbCheck.php
  src/Interfaces/Check.php
  src/Traits/Translatable.php
Labels: enhancement

#59 Adding missing Keys to German Translation
  resources/lang/de.json
Labels: translations
